window.APP_CONFIG = {
  "headers": [
    "Origem",
    "Dossiê ou Item?",
    "Número sequencial",
    "DATA ARQ.",
    "Ano de arquivamento",
    "Cadastrado em",
    "TIPO DOC.",
    "DESCRIÇÃO",
    "NUMERAÇÃO",
    "DATA ABRANGENTE",
    "Órgão Julgador",
    "Código (PCTT)",
    "Prazo de Guarda PCTT (Arquivo Corrente) (em anos)",
    "Prazo de Guarda PCTT (Arquivo intermediário) (em anos)",
    "Destinação Final",
    "Eliminar em (NÃO ALTERAR - FÓRMULA)",
    "CÓDIGO DE CLASSIFICAÇÃO ADICIONAL",
    "OBS:",
    "ENDEREÇO (CAIXA) (anterior)",
    "ENDEREÇO ANTERIOR",
    "ENDEREÇO (CAIXA) (atual)",
    "Tipo de Caixa",
    "UNIDADE",
    "Status (arquivado, eliminado, a eliminar)",
    "Data de Eliminação",
    "Situação da Revisão",
    "ONDE PAREI",
    "Caixa atual diz que tem documento?",
    "Informação atualizada?"
  ],
  "dropdowns": {
    "Situação da Revisão": [
      "Manter",
      "Excluir",
      "Dúvida"
    ],
    "Caixa atual diz que tem documento?": [
      "Sim",
      "Não"
    ]
  },
  "formulaColumn": 16,
  "sectors": [
    "Presidência",
    "Vice-Presidência",
    "Assessoria de Recursos - AREC",
    "Corregedoria",
    "Ouvidoria",
    "Assessoria de Concursos para Magistrados e Apoio Especializado - ACMA",
    "Conselho de Administração",
    "Diretoria Geral - DG",
    "Assessoria de Comunicação - ACOM",
    "Assessoria de Relações Institucionais e Cerimonial - ARIC",
    "Secretaria Auditoria Interna - SAI",
    "Secretaria de Atividades Administrativas - SAT",
    "Secretaria de Infraestrutura e Logística - SIE",
    "Secretaria de Atividades Judiciárias - SAJ",
    "Secretaria de Tecnologia da Informação - STI",
    "Serviço de Informação ao Cidadão - SIC",
    "Secretaria de Planejamento, Orçamento e Finanças - SPO",
    "Secretaria de Gestão de Pessoas - SGP",
    "Subsecretaria do Tribunal Pleno, Órgão Especial e Seções Especializadas",
    "Subsecretaria da 1ª Turma Especializada",
    "Subsecretaria da 2ª Turma Especializada",
    "Subsecretaria da 3ª Turma Especializada",
    "Subsecretaria da 4ª Turma Especializada",
    "Subsecretaria da 5ª Turma Especializada",
    "Subsecretaria da 6ª Turma Especializada",
    "Subsecretaria da 7ª Turma Especializada",
    "Subsecretaria da 8ª Turma Especializada"
  ],
  "address": "Rua Acre, 80 - Centro - Rio de Janeiro/RJ",
  "sourceNote": "Setores conforme página oficial de contatos do TRF2, atualizada em 16/09/2026."
};