(()=>{const c=APP_CONFIG,fields=c.headers,drop=new Set(Object.keys(c.dropdowns)),formula=c.headers[c.formulaColumn-1],records=[];
const $=x=>document.getElementById(x),slug=s=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
const esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[x]));
function toast(s){let t=$("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}
function build(){let g=$("formGrid");g.innerHTML="";fields.forEach(n=>{let w=document.createElement("div");w.className="field";let l=document.createElement("label");l.textContent=n;let x;
if(drop.has(n)){x=document.createElement("select");x.innerHTML='<option value="">Selecionar...</option>'+c.dropdowns[n].map(v=>`<option>${esc(v)}</option>`).join("")}
else if(n===formula){w.classList.add("readonly");x=document.createElement("input");x.readOnly=true;x.placeholder="Calculado no Excel"}
else if(["DESCRIÇÃO","OBS:","ENDEREÇO ANTERIOR"].includes(n)){x=document.createElement("textarea")}
else x=document.createElement("input");
x.id="f_"+slug(n);x.dataset.field=n;w.append(l,x);g.append(w)})}build();
function prog(p,s){$("progressBox").classList.remove("hidden");$("progressBar").style.width=p+"%";$("progressPct").textContent=Math.round(p)+"%";$("progressText").textContent=s}
async function pdfCanvases(file){let pdfjs=globalThis.pdfjsLib;if(!pdfjs)throw Error("PDF.js ainda não carregou; tente novamente.");let pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise,a=[];for(let p=1;p<=pdf.numPages;p++){prog(5+p/pdf.numPages*20,"Renderizando página "+p+" de "+pdf.numPages+"...");let page=await pdf.getPage(p),v=page.getViewport({scale:1.8}),x=document.createElement("canvas");x.width=v.width;x.height=v.height;await page.render({canvasContext:x.getContext("2d"),viewport:v}).promise;a.push(x)}return a}
async function imgCanvas(file){let u=URL.createObjectURL(file);try{let im=await new Promise((r,j)=>{let i=new Image;i.onload=()=>r(i);i.onerror=j;i.src=u}),m=2400,s=Math.min(1,m/Math.max(im.naturalWidth,im.naturalHeight)),x=document.createElement("canvas");x.width=im.naturalWidth*s;x.height=im.naturalHeight*s;x.getContext("2d").drawImage(im,0,0,x.width,x.height);return[x]}finally{URL.revokeObjectURL(u)}}
function norm(s){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function after(t,labels){let a=t.split(/\n/).map(x=>x.trim()).filter(Boolean);for(let q of labels){q=norm(q);for(let i=0;i<a.length;i++)if(norm(a[i]).includes(q)){let z=a[i].split(/[:;-]/).slice(1).join(" ").trim();return z||a[i+1]||""}}return""}
function match(t,r){let m=t.match(r);return m?m[1].trim():""}
function sector(t){let n=norm(t);for(let s of c.sectors)if(n.includes(norm(s)))return s;return""}
function map(t){let v={};v["Origem"]=sector(t);v["UNIDADE"]=sector(t);v["Número sequencial"]=match(t,/(?:sequencial|n[ºo°]?\s*sequencial)[^\d]{0,10}(\d+)/i);v["DATA ARQ."]=match(t,/(?:data(?:\s+de\s+(?:arquivo|arquivamento|documento))?)[^0-9]{0,12}(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})/i);v["Ano de arquivamento"]=match(t,/(?:ano(?:\s+de\s+arquivamento)?)[^0-9]{0,12}((?:19|20)\d{2})/i)||match(t,/\b((?:19|20)\d{2})\b/);
v["TIPO DOC."]=after(t,["tipo doc","tipo de documento","espécie documental"]);v["DESCRIÇÃO"]=after(t,["descrição","assunto","documento"]);v["NUMERAÇÃO"]=after(t,["numeração","numero do documento","número do documento"]);v["DATA ABRANGENTE"]=after(t,["data abrangente","período","período abrangido"]);v["Órgão Julgador"]=after(t,["órgão julgador","orgao julgador"]);v["Código (PCTT)"]=after(t,["código (pctt)","código pctt","pctt"]);v["Prazo de Guarda PCTT (Arquivo Corrente) (em anos)"]=after(t,["arquivo corrente"]);v["Prazo de Guarda PCTT (Arquivo intermediário) (em anos)"]=after(t,["arquivo intermediário"]);v["Destinação Final"]=after(t,["destinação final","destinacao final"]);v["CÓDIGO DE CLASSIFICAÇÃO ADICIONAL"]=after(t,["classificação adicional","codigo de classificacao adicional"]);v["OBS:"]=after(t,["obs","observação","observacoes"]);v["ENDEREÇO (CAIXA) (anterior)"]=match(t,/(?:caixa|cx\.?|endereço\s*\(?caixa\)?)[^A-Za-z0-9]{0,10}(E\s*\/\s*[0-9A-Z-]+)/i)||match(t,/\b(E\s*\/\s*[0-9]{1,6})\b/i);v["ENDEREÇO (CAIXA) (atual)"]=v["ENDEREÇO (CAIXA) (anterior)"];v["ENDEREÇO ANTERIOR"]=after(t,["endereço anterior"]);v["Tipo de Caixa"]=after(t,["tipo de caixa"]);v["Data de Eliminação"]=after(t,["data de eliminação","eliminação"]);v["ONDE PAREI"]=after(t,["onde parei"]);return v}
async function process(file){try{prog(2,"Abrindo arquivo...");let cs=file.type==="application/pdf"?await pdfCanvases(file):await imgCanvas(file),txt="";for(let i=0;i<cs.length;i++){let w=await Tesseract.createWorker("por",1,{logger:m=>m.status==="recognizing text"&&prog(25+(m.progress||0)*65,"Lendo texto...")}),r=await w.recognize(cs[i]);txt+="\n"+r.data.text;await w.terminate();cs[i].width=cs[i].height=0}let v=map(txt);fields.forEach(n=>{if(!drop.has(n)&&n!==formula&&v[n])$("f_"+slug(n)).value=v[n]});prog(100,"Leitura concluída");toast("Documento lido. Revise os campos.");setTimeout(()=>$("progressBox").classList.add("hidden"),1000)}catch(e){prog(0,"Erro: "+e.message);toast(e.message)}}
$("fileInput").onchange=e=>process(e.target.files[0]);$("cameraInput").onchange=e=>process(e.target.files[0]);
function form(){let r={};fields.forEach(n=>r[n]=$("f_"+slug(n))?.value.trim()||"");return r}
function render(){let w=$("tableWrap");$("count").textContent=records.length;if(!records.length){w.innerHTML='<div class="empty">Nenhum registro adicionado.</div>';return}w.innerHTML="<table><thead><tr>"+fields.map(n=>"<th>"+esc(n)+"</th>").join("")+"<th>Ações</th></tr></thead><tbody>"+records.map((r,i)=>"<tr>"+fields.map(n=>"<td>"+esc(r[n])+"</td>").join("")+`<td><button class="danger" data-d="${i}">Excluir</button></td></tr>`).join("")+"</tbody></table>";w.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{records.splice(+b.dataset.d,1);render()})}
$("addBtn").onclick=()=>{let r=form();if(!r.Origem&&!r["DESCRIÇÃO"]&&!r["ENDEREÇO (CAIXA) (atual)"]){toast("Preencha os campos principais.");return}records.push(r);render();fields.forEach(n=>{let x=$("f_"+slug(n));if(x)x.value=""});toast("Registro adicionado.")};
$("clearBtn").onclick=()=>fields.forEach(n=>{let x=$("f_"+slug(n));if(x)x.value=""});
function date(v){let m=String(v).match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})$/);if(!m)return v;let y=+m[3];if(y<100)y+=2000;return new Date(y,+m[2]-1,+m[1])}
$("exportBtn").onclick=()=>{if(!records.length){toast("Adicione pelo menos um registro.");return}let a=[fields];records.forEach((r,i)=>{let row=fields.map(n=>r[n]||"");let d=fields.indexOf("DATA ARQ.");if(d>=0)row[d]=date(row[d]);row[c.formulaColumn-1]=`=IF(OR(D${i+2}="",N${i+2}=""),"",DATE(YEAR(D${i+2})+N${i+2}+1,MONTH(D${i+2}),DAY(D${i+2})))`;a.push(row)});let w=XLSX.utils.book_new(),s=XLSX.utils.aoa_to_sheet(a);s["!cols"]=fields.map(n=>({wch:Math.min(42,Math.max(12,String(n).length+2))}));XLSX.utils.book_append_sheet(w,s,"Plan1");XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([["ENDEREÇO (CAIXA)","UNIDADE"]]),"Plan2");XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([["ENDEREÇO (CAIXA)"]]),"Plan3");XLSX.writeFile(w,"Inventario_TRF2_OCR.xlsx");toast("Excel exportado.")};
})();